server:
  port: 8083

spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ridelink_ride_db}

services:
  account-service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
  driver-service:
    url: ${DRIVER_SERVICE_URL:http://localhost:8082}
  fare-service:
    url: ${FARE_SERVICE_URL:http://localhost:8084}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
